spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: scanner
        resources:
          requests:
            memory: "1200Mi"
            cpu: "600m"
          limits:
            memory: "4Gi"
            cpu: "2500m"
