spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: scanner
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "2503Mi"
            cpu: "2000m"
