apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  namespace: stackrox
  name: stackrox-secured-cluster-services
spec:
  clusterName: my-cluster
  scanner:
    scannerComponent: AutoSense
  centralEndpoint: central-stackrox.apps.rt-03-07-fascinated-baby-tremble.openshift.infra.rox.systems:443
