name: PR Workflow
on:
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  style-checks:
    runs-on: ubuntu-latest
    container:
      image: quay.io/rhacs-eng/apollo-ci:0.3.28
      credentials:
        username: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
        password: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
      env:
        ORG_TOKEN_FOR_GITHUB: ${{ secrets.ORG_TOKEN_FOR_GITHUB }}
      options: --user 0 --cpus 2
    steps:
      - name: Determine cache paths
        id: cache-paths
        run: |
          echo "::set-output name=GOCACHE::$(go env GOCACHE)"
          echo "::set-output name=GOMODCACHE::$(go env GOMODCACHE)"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Go Cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.cache-paths.outputs.GOCACHE }}
            ${{ steps.cache-paths.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-go-v1-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-v1-
      - name: Run style checks
        run: |
          ./scripts/ci/style-checks.sh
