name: PR Workflow
on:
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    env:
      ORG_TOKEN_FOR_GITHUB: ${{ secrets.ORG_TOKEN_FOR_GITHUB }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - name: Get private repo access
        run: |
          ./scripts/ci/github.sh get_private_repo_access
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44.0
          args: --timeout=20m
          skip-go-installation: true

  # style-checks:
  #   runs-on: ubuntu-latest
  #   env:
  #     ORG_TOKEN_FOR_GITHUB: ${{ secrets.ORG_TOKEN_FOR_GITHUB }}
  #   # container:
  #   #   image: quay.io/rhacs-eng/apollo-ci:0.3.28
  #   #   credentials:
  #   #     username: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
  #   #     password: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
  #   #   env:
  #   #     ORG_TOKEN_FOR_GITHUB: ${{ secrets.ORG_TOKEN_FOR_GITHUB }}
  #   #   options: --user 0 --cpus 2
  #   steps:
  #     - name: Setup Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: '1.17.2'
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Restore Go Cache
  #       uses: actions/cache@v2
  #       with:
  #         path: |
  #           ~/.cache/go-build
  #           ~/go/pkg/mod
  #         key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
  #         restore-keys: |
  #           ${{ runner.os }}-go-
  #     - name: Run style checks
  #       run: |
  #         ./scripts/ci/style-checks.sh
