name: Tasks for a developers pull request
on:
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  style-checks:
    runs-on: ubuntu-latest
    container:
      image: quay.io/rhacs-eng/apollo-ci:0.3.28
      credentials:
        username: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
        password: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run style checks
        run: |
          ls
