name: PR Workflow
on:
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  style-checks:
    runs-on: ubuntu-latest
    container:
      image: quay.io/rhacs-eng/apollo-ci:0.3.28
      credentials:
        username: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
        password: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
      env:
        ORG_TOKEN_FOR_GITHUB: ${{ secrets.ORG_TOKEN_FOR_GITHUB }}
      options: --user 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run style checks
        run: |
          ./scripts/ci/style-checks.sh
