name: PR Workflow
on:
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  style-checks:
    runs-on: ubuntu-latest
    env:
      MONOREPO_LOCK: ui/monorepo.lock
    container:
      image: quay.io/rhacs-eng/apollo-ci:0.3.28
      credentials:
        username: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
        password: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
      env:
        ORG_TOKEN_FOR_GITHUB: ${{ secrets.ORG_TOKEN_FOR_GITHUB }}
      options: --user 0 --cpus 2
    steps:
      - name: Determine Go cache paths
        id: cache-paths
        run: |
          echo "::set-output name=GOCACHE::$(go env GOCACHE)"
          echo "::set-output name=GOMODCACHE::$(go env GOMODCACHE)"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Go Cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.cache-paths.outputs.GOCACHE }}
            ${{ steps.cache-paths.outputs.GOMODCACHE }}
            /github/home/.cache/go-build
            /github/home/.cache/golangci-lint
            /github/home/.cache/staticcheck
          key: ${{ runner.os }}-go-v2-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-v2-

      - name: Restore Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            /root/.gradle/caches
          key: ${{ runner.os }}-gradle-v2-${{ hashFiles('qa-tests-backend/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v2-

      - name: Create combined mono repo lock file & digest
        id: create-concatenated-ui-monorepo-lock
        run: |
          echo "Creating combined lock in: ${{ env.MONOREPO_LOCK }}"
          find ui/ -type d \( -name node_modules \) -prune -false -o -name package.json -print0 | sort -z | xargs -r0 cat > ${{ env.MONOREPO_LOCK }}
          cat ui/yarn.lock >> ${{ env.MONOREPO_LOCK }}

      - name: Restore NPM Cache
        uses: actions/cache@v2
        with:
          path: |
            ui/deps
            /github/home/.cache/Cypress
            /usr/local/share/.cache
            ui/node_modules
            ui/apps/platform/node_modules
            ui/packages/ui-components/node_modules
            ui/packages/tailwind-config/node_modules
          key: ${{ runner.os }}-npm-v2-${{ hashFiles(env.MONOREPO_LOCK) }}
          restore-keys: |
            ${{ runner.os }}-npm-v2-
            
      - name: Run style checks
        run: |
          ./scripts/ci/style-checks.sh
